# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]
handlers:
- url: /
  static_files: dist/equifax-front/index.html
  upload: dist/equifax-front/index.html
- url: /(.*\.(js|css|svg|png|json|woff|jpg)(|\.map))$
  static_files: dist/equifax-front/\1
  upload: dist/equifax-front/(.*)(|\.map)
- url: /.*
  static_files: dist/equifax-front/index.html
  upload: dist/equifax-front/.*
skip_files:
- ^(?!dist)  # Skip any files not in the dist folder